### ISSUE TITLE
Overlay Color Not Working

### ISSUE THREAD

**Issue by jte369** [cr4ckp0t/ElvUI_FogofWar#1]
The settings for this appear in their own section, called "Plugins by Crackpotx", instead of "Plugins", where I would expect them, but the main thing is: setting an overlay color does nothing.  Unexplored areas are not colored with it, as you would expect.
I'm using this add-on with ElvUI 11.20

**Comment by cr4ckp0t** [comment]
It is something with Blizzard's API. There does not appear to be anything I can do about it.
