### ISSUE TITLE
Not working ? (Dragonflight)

### ISSUE THREAD

**Issue by KatyPurry** [cr4ckp0t/ElvUI_FogofWar#10]
Hello,

It seems doens'work on my installation :

WoW Beta 10.0.2 (46259)
ElvUI 12.98
Fog of War : 4.2.7
French client

![image](https://user-images.githubusercontent.com/89610869/198906199-13f83cc1-5ca2-4e13-a049-0f114660306b.png)

![image](https://user-images.githubusercontent.com/89610869/198906191-b4ca20f0-4c26-4dd8-8004-e4c180e18248.png)

**Comment by cr4ckp0t** [comment]
The beta client is not supported and nor are the new zones.
