### ISSUE TITLE
Classic support?

### ISSUE THREAD

**Issue by crborga** [cr4ckp0t/ElvUI_FogofWar#3]
I was wondering if you could add support for wow classic with ElvUI Classic. Currently Mapster works but not correctly.

**Comment by crborga** [comment]
I made a fan update for Classic. Everything seems to work except setting the overlay color. 
[ElvUI_FogofWar.zip](https://github.com/cr4ckp0t/ElvUI_FogofWar/files/3992776/ElvUI_FogofWar.zip)

**Comment by cr4ckp0t** [comment]
I do not play Classic and have no intention of porting any of my addons over to it. Sorry. Feel free to fork any of them and port them over.
