### ISSUE TITLE
overlay notworking 

### ISSUE THREAD

**Issue by Flnnx** [cr4ckp0t/ElvUI_FogofWar#6]
the overlay colors not working i tried using mapster and it worked but i rly dont like that addon

**Comment by crborga** [comment]
This is a known problem. Not sure if there is a way to fix it.

**Comment by JVemmer** [comment]
Since Mapster can do it, there is without a doubt at least one way to fix it. I am sadly not lua-savvy enough to propose a solution.

**Comment by cr4ckp0t** [comment]
It was actually an issue with the config not setting the DB var properly. It has been fixed in version 4.2.0 and is working properly.
