### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by martinboy1974** [cr4ckp0t/ElvUI_FogofWar#7]
The addon is giving me 2 lua errors in version 4.1.0

I am using ElvUI 12.14

Lua error 1:
1x AceLocale-3.0-6: ElvUI_FogofWar: Missing entry for 'Plugins by Crackpotx'
[string "@ElvUI_FogofWar\ElvUI_FogofWar-4.1.0.lua"]:2207: in function `callback'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1069: in function `ToggleOptionsUI'
[string "@ElvUI_SLE\core\gameMenu.lua"]:13: in function <ElvUI_SLE\core\gameMenu.lua:13>

Lua error 2:
1x AceLocale-3.0-6: ElvUI_FogofWar: Missing entry for 'Thanks for using and supporting my work!  -- Crackpotx

If you find any bugs, or have any suggestions for any of my addons, please open a ticket at that particular addon's page on CurseForge.'
[string "@ElvUI_FogofWar\ElvUI_FogofWar-4.1.0.lua"]:2212: in function `callback'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1069: in function `ToggleOptionsUI'
[string "@ElvUI_SLE\core\gameMenu.lua"]:13: in function <ElvUI_SLE\core\gameMenu.lua:13>

**Comment by crborga** [comment]
```
2x AceLocale-3.0-6: ElvUI_FogofWar: Missing entry for 'Thanks for using and supporting my work!  -- Crackpotx

If you find any bugs, or have any suggestions for any of my addons, please open a ticket at that particular addon's page on CurseForge.'
[string "@ElvUI_FogofWar\ElvUI_FogofWar-4.1.0.lua"]:2212: in function `callback'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1069: in function <ElvUI\Core\Config.lua:1056>
[string "=[C]"]: in function `ToggleOptionsUI'
[string "@ElvUI\init.lua"]:213: in function <ElvUI\init.lua:212>
```

```
2x AceLocale-3.0-6: ElvUI_FogofWar: Missing entry for 'Plugins by Crackpotx'
[string "@ElvUI_FogofWar\ElvUI_FogofWar-4.1.0.lua"]:2207: in function `callback'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1069: in function <ElvUI\Core\Config.lua:1056>
[string "=[C]"]: in function `ToggleOptionsUI'
[string "@ElvUI\init.lua"]:213: in function <ElvUI\init.lua:212>
```

**Comment by crborga** [comment]
Pretty sure it's related to the locale

**Comment by crborga** [comment]
> The addon is giving me 2 lua errors in version 4.1.0
> 
> I am using ElvUI 12.14
> 
> Lua error 1:
> 1x AceLocale-3.0-6: ElvUI_FogofWar: Missing entry for 'Plugins by Crackpotx'
> [string "@ElvUI_FogofWar\ElvUI_FogofWar-4.1.0.lua"]:2207: in function `callback' [string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161> [string "=[C]"]: ? [string "@ElvUI\Core\Config.lua"]:1069: in function `ToggleOptionsUI'
> [string "@ElvUI_SLE\core\gameMenu.lua"]:13: in function <ElvUI_SLE\core\gameMenu.lua:13>
> 
> Lua error 2:
> 1x AceLocale-3.0-6: ElvUI_FogofWar: Missing entry for 'Thanks for using and supporting my work! -- Crackpotx
> 
> If you find any bugs, or have any suggestions for any of my addons, please open a ticket at that particular addon's page on CurseForge.'
> [string "@ElvUI_FogofWar\ElvUI_FogofWar-4.1.0.lua"]:2212: in function `callback' [string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161> [string "=[C]"]: ? [string "@ElvUI\Core\Config.lua"]:1069: in function `ToggleOptionsUI'
> [string "@ElvUI_SLE\core\gameMenu.lua"]:13: in function <ElvUI_SLE\core\gameMenu.lua:13>

Try this https://github.com/crborga/ElvUI_FogofWar/archive/4.1.1.zip

**Comment by martinboy1974** [comment]
That seems to have fixed it.

**Comment by crborga** [comment]
Push request should fix this.

**Comment by crborga** [comment]
That seems to have fixed it.

Good I made a push request so main project should be updated whenever it's approved. #8

**Comment by crborga** [comment]
This should a little better not sure it will be noticeable difference though.
https://github.com/crborga/ElvUI_FogofWar/archive/master.zip

**Comment by cr4ckp0t** [comment]
The packager from CurseForge should be including the localizations. I updated them once again before pushing the latest version, so hopefully this will correct the issue.
